# Generated by Django 4.2.6 on 2023-10-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("roster_positions", models.CharField(max_length=200)),
                ("draft_id", models.IntegerField()),
                ("scoring_settings", models.CharField(max_length=200)),
                ("season", models.IntegerField()),
                ("divisions", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                ("team_name", models.CharField(max_length=200)),
                ("team_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("roster", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_name", models.CharField(max_length=200)),
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=200)),
                ("avatar", models.CharField(max_length=200)),
                ("team_id", models.IntegerField()),
            ],
        ),
    ]
