# Generated by Django 4.2.26 on 2026-01-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasyleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('team1_score', models.FloatField(default=0.0)),
                ('team2_score', models.FloatField(default=0.0)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('is_playoff', models.BooleanField(default=False)),
                ('is_championship', models.BooleanField(default=False)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team1', to='fantasyleague.teams')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups_as_team2', to='fantasyleague.teams')),
            ],
            options={
                'verbose_name': 'Matchup',
                'verbose_name_plural': 'Matchups',
                'ordering': ['-season', '-week', 'match_date'],
            },
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('conference', models.CharField(blank=True, choices=[('AFC', 'AFC'), ('NFC', 'NFC')], max_length=3)),
                ('division', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'NFL Team',
                'verbose_name_plural': 'NFL Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('fantasy_points', models.FloatField(default=0.0)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='fantasyleague.matchup')),
                ('nfl_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_scores', to='fantasyleague.nflteam')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='fantasyleague.teams')),
            ],
            options={
                'verbose_name': 'Player Score',
                'verbose_name_plural': 'Player Scores',
                'ordering': ['-fantasy_points'],
            },
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('ties', models.IntegerField(default=0)),
                ('total_points', models.FloatField(default=0.0)),
                ('average_points', models.FloatField(default=0.0)),
                ('playoff_appearance', models.BooleanField(default=False)),
                ('championship', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='fantasyleague.teams')),
            ],
            options={
                'verbose_name': 'Team Ranking',
                'verbose_name_plural': 'Team Rankings',
                'ordering': ['-season', 'rank'],
                'unique_together': {('team', 'season')},
            },
        ),
        migrations.CreateModel(
            name='NFLTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('total_fantasy_points', models.FloatField(default=0.0)),
                ('games_played', models.IntegerField(default=0)),
                ('average_points', models.FloatField(default=0.0)),
                ('total_touchdowns', models.IntegerField(default=0)),
                ('total_yards', models.IntegerField(default=0)),
                ('passing_yards', models.IntegerField(default=0)),
                ('rushing_yards', models.IntegerField(default=0)),
                ('receiving_yards', models.IntegerField(default=0)),
                ('nfl_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fantasyleague.nflteam')),
            ],
            options={
                'verbose_name': 'NFL Team Stat',
                'verbose_name_plural': 'NFL Team Stats',
                'ordering': ['-season', 'nfl_team'],
                'unique_together': {('nfl_team', 'season')},
            },
        ),
    ]
